cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: exampleproject
project_slug_no_hyphen: exampleproject
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: thilobru
creator_github_username: thilobru
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Thilo Brummerloh
email: tb49leli@studserv.uni-leipzig.de
project_name: exampleproject
project_short_description: example
version: 0.1.0
license: MIT
